
local:
  log_to_file: "yes"
  log_to_console: "yes"
  log_file_path: C:\Users\nithi\VS_CODE\MYSQL-REDSHIFT-PIPELINE\src
  log_file_name: "replica-logs"
  db_host: "magesh.106501636072.us-east-1.redshift-serverless.amazonaws.com"
  db_port: "5439"
  db_user: "admin"
  db_password: "AWSMagesh1"
  db_name: "dev"
  db_schema: "public"
  database_type: "redshift"
  mysql_db_host: "localhost"
  mysql_db_port: 3306
  mysql_db_user: "root"
  mysql_db_password: "mypass"
  mysql_db_name: "test"
  mysql_db_schema: "public"

#  "jdbc:redshift://magesh.106501636072.us-east-1.redshift-serverless.amazonaws.com:5439/dev"